/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OauthRouteRouteImport } from './routes/oauth/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/_settings/route'
import { Route as AuthenticatedLegacyRouteRouteImport } from './routes/_authenticated/_legacy/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app/index'
import { Route as AuthInviteTokenRouteImport } from './routes/auth/invite.$token'
import { Route as AuthenticatedSettingsSettingsRouteImport } from './routes/_authenticated/_settings/settings'
import { Route as AuthenticatedLegacySetupRouteImport } from './routes/_authenticated/_legacy/setup'
import { Route as AuthenticatedLegacyOauthCallbackRouteImport } from './routes/_authenticated/_legacy/oauth-callback'
import { Route as AuthenticatedAppTasteRouteImport } from './routes/_authenticated/_app/taste'
import { Route as AuthenticatedAppRequestsRouteImport } from './routes/_authenticated/_app/requests'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/_app/profile'
import { Route as AuthenticatedAppActivityRouteImport } from './routes/_authenticated/_app/activity'
import { Route as AuthenticatedSettingsSettingsIndexRouteImport } from './routes/_authenticated/_settings/settings/index'
import { Route as AuthenticatedSettingsSettingsSecurityRouteImport } from './routes/_authenticated/_settings/settings/security'
import { Route as AuthenticatedSettingsSettingsProfileRouteImport } from './routes/_authenticated/_settings/settings/profile'
import { Route as AuthenticatedSettingsSettingsDangerRouteImport } from './routes/_authenticated/_settings/settings/danger'
import { Route as AuthenticatedSettingsSettingsConnectionsRouteImport } from './routes/_authenticated/_settings/settings/connections'
import { Route as AuthenticatedSettingsSettingsAppsRouteImport } from './routes/_authenticated/_settings/settings/apps'
import { Route as AuthenticatedLegacyAdminUsersRouteImport } from './routes/_authenticated/_legacy/admin/users'
import { Route as AuthenticatedLegacyAdminServerRouteImport } from './routes/_authenticated/_legacy/admin/server'
import { Route as AuthenticatedLegacyAdminRolesRouteImport } from './routes/_authenticated/_legacy/admin/roles'
import { Route as AuthenticatedLegacyAdminPluginsRouteImport } from './routes/_authenticated/_legacy/admin/plugins'
import { Route as AuthenticatedLegacyAdminLogsRouteImport } from './routes/_authenticated/_legacy/admin/logs'
import { Route as AuthenticatedLegacyAdminJobsRouteImport } from './routes/_authenticated/_legacy/admin/jobs'

const OauthRouteRoute = OauthRouteRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => OauthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/_settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLegacyRouteRoute =
  AuthenticatedLegacyRouteRouteImport.update({
    id: '/_legacy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthInviteTokenRoute = AuthInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedSettingsSettingsRoute =
  AuthenticatedSettingsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedLegacySetupRoute =
  AuthenticatedLegacySetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => AuthenticatedLegacyRouteRoute,
  } as any)
const AuthenticatedLegacyOauthCallbackRoute =
  AuthenticatedLegacyOauthCallbackRouteImport.update({
    id: '/oauth-callback',
    path: '/oauth-callback',
    getParentRoute: () => AuthenticatedLegacyRouteRoute,
  } as any)
const AuthenticatedAppTasteRoute = AuthenticatedAppTasteRouteImport.update({
  id: '/taste',
  path: '/taste',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppRequestsRoute =
  AuthenticatedAppRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppActivityRoute =
  AuthenticatedAppActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedSettingsSettingsIndexRoute =
  AuthenticatedSettingsSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsSettingsRoute,
  } as any)
const AuthenticatedSettingsSettingsSecurityRoute =
  AuthenticatedSettingsSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsSettingsRoute,
  } as any)
const AuthenticatedSettingsSettingsProfileRoute =
  AuthenticatedSettingsSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsSettingsRoute,
  } as any)
const AuthenticatedSettingsSettingsDangerRoute =
  AuthenticatedSettingsSettingsDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => AuthenticatedSettingsSettingsRoute,
  } as any)
const AuthenticatedSettingsSettingsConnectionsRoute =
  AuthenticatedSettingsSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedSettingsSettingsRoute,
  } as any)
const AuthenticatedSettingsSettingsAppsRoute =
  AuthenticatedSettingsSettingsAppsRouteImport.update({
    id: '/apps',
    path: '/apps',
    getParentRoute: () => AuthenticatedSettingsSettingsRoute,
  } as any)
const AuthenticatedLegacyAdminUsersRoute =
  AuthenticatedLegacyAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedLegacyRouteRoute,
  } as any)
const AuthenticatedLegacyAdminServerRoute =
  AuthenticatedLegacyAdminServerRouteImport.update({
    id: '/admin/server',
    path: '/admin/server',
    getParentRoute: () => AuthenticatedLegacyRouteRoute,
  } as any)
const AuthenticatedLegacyAdminRolesRoute =
  AuthenticatedLegacyAdminRolesRouteImport.update({
    id: '/admin/roles',
    path: '/admin/roles',
    getParentRoute: () => AuthenticatedLegacyRouteRoute,
  } as any)
const AuthenticatedLegacyAdminPluginsRoute =
  AuthenticatedLegacyAdminPluginsRouteImport.update({
    id: '/admin/plugins',
    path: '/admin/plugins',
    getParentRoute: () => AuthenticatedLegacyRouteRoute,
  } as any)
const AuthenticatedLegacyAdminLogsRoute =
  AuthenticatedLegacyAdminLogsRouteImport.update({
    id: '/admin/logs',
    path: '/admin/logs',
    getParentRoute: () => AuthenticatedLegacyRouteRoute,
  } as any)
const AuthenticatedLegacyAdminJobsRoute =
  AuthenticatedLegacyAdminJobsRouteImport.update({
    id: '/admin/jobs',
    path: '/admin/jobs',
    getParentRoute: () => AuthenticatedLegacyRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/oauth': typeof OauthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/activity': typeof AuthenticatedAppActivityRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/requests': typeof AuthenticatedAppRequestsRoute
  '/taste': typeof AuthenticatedAppTasteRoute
  '/oauth-callback': typeof AuthenticatedLegacyOauthCallbackRoute
  '/setup': typeof AuthenticatedLegacySetupRoute
  '/settings': typeof AuthenticatedSettingsSettingsRouteWithChildren
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/admin/jobs': typeof AuthenticatedLegacyAdminJobsRoute
  '/admin/logs': typeof AuthenticatedLegacyAdminLogsRoute
  '/admin/plugins': typeof AuthenticatedLegacyAdminPluginsRoute
  '/admin/roles': typeof AuthenticatedLegacyAdminRolesRoute
  '/admin/server': typeof AuthenticatedLegacyAdminServerRoute
  '/admin/users': typeof AuthenticatedLegacyAdminUsersRoute
  '/settings/apps': typeof AuthenticatedSettingsSettingsAppsRoute
  '/settings/connections': typeof AuthenticatedSettingsSettingsConnectionsRoute
  '/settings/danger': typeof AuthenticatedSettingsSettingsDangerRoute
  '/settings/profile': typeof AuthenticatedSettingsSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSettingsSecurityRoute
  '/settings/': typeof AuthenticatedSettingsSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/oauth': typeof OauthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/activity': typeof AuthenticatedAppActivityRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/requests': typeof AuthenticatedAppRequestsRoute
  '/taste': typeof AuthenticatedAppTasteRoute
  '/oauth-callback': typeof AuthenticatedLegacyOauthCallbackRoute
  '/setup': typeof AuthenticatedLegacySetupRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/admin/jobs': typeof AuthenticatedLegacyAdminJobsRoute
  '/admin/logs': typeof AuthenticatedLegacyAdminLogsRoute
  '/admin/plugins': typeof AuthenticatedLegacyAdminPluginsRoute
  '/admin/roles': typeof AuthenticatedLegacyAdminRolesRoute
  '/admin/server': typeof AuthenticatedLegacyAdminServerRoute
  '/admin/users': typeof AuthenticatedLegacyAdminUsersRoute
  '/settings/apps': typeof AuthenticatedSettingsSettingsAppsRoute
  '/settings/connections': typeof AuthenticatedSettingsSettingsConnectionsRoute
  '/settings/danger': typeof AuthenticatedSettingsSettingsDangerRoute
  '/settings/profile': typeof AuthenticatedSettingsSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSettingsSecurityRoute
  '/settings': typeof AuthenticatedSettingsSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/oauth': typeof OauthRouteRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/_legacy': typeof AuthenticatedLegacyRouteRouteWithChildren
  '/_authenticated/_settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_authenticated/_app/activity': typeof AuthenticatedAppActivityRoute
  '/_authenticated/_app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/_app/requests': typeof AuthenticatedAppRequestsRoute
  '/_authenticated/_app/taste': typeof AuthenticatedAppTasteRoute
  '/_authenticated/_legacy/oauth-callback': typeof AuthenticatedLegacyOauthCallbackRoute
  '/_authenticated/_legacy/setup': typeof AuthenticatedLegacySetupRoute
  '/_authenticated/_settings/settings': typeof AuthenticatedSettingsSettingsRouteWithChildren
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/_legacy/admin/jobs': typeof AuthenticatedLegacyAdminJobsRoute
  '/_authenticated/_legacy/admin/logs': typeof AuthenticatedLegacyAdminLogsRoute
  '/_authenticated/_legacy/admin/plugins': typeof AuthenticatedLegacyAdminPluginsRoute
  '/_authenticated/_legacy/admin/roles': typeof AuthenticatedLegacyAdminRolesRoute
  '/_authenticated/_legacy/admin/server': typeof AuthenticatedLegacyAdminServerRoute
  '/_authenticated/_legacy/admin/users': typeof AuthenticatedLegacyAdminUsersRoute
  '/_authenticated/_settings/settings/apps': typeof AuthenticatedSettingsSettingsAppsRoute
  '/_authenticated/_settings/settings/connections': typeof AuthenticatedSettingsSettingsConnectionsRoute
  '/_authenticated/_settings/settings/danger': typeof AuthenticatedSettingsSettingsDangerRoute
  '/_authenticated/_settings/settings/profile': typeof AuthenticatedSettingsSettingsProfileRoute
  '/_authenticated/_settings/settings/security': typeof AuthenticatedSettingsSettingsSecurityRoute
  '/_authenticated/_settings/settings/': typeof AuthenticatedSettingsSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/oauth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/oauth/consent'
    | '/activity'
    | '/profile'
    | '/requests'
    | '/taste'
    | '/oauth-callback'
    | '/setup'
    | '/settings'
    | '/auth/invite/$token'
    | '/admin/jobs'
    | '/admin/logs'
    | '/admin/plugins'
    | '/admin/roles'
    | '/admin/server'
    | '/admin/users'
    | '/settings/apps'
    | '/settings/connections'
    | '/settings/danger'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/oauth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/oauth/consent'
    | '/activity'
    | '/profile'
    | '/requests'
    | '/taste'
    | '/oauth-callback'
    | '/setup'
    | '/auth/invite/$token'
    | '/admin/jobs'
    | '/admin/logs'
    | '/admin/plugins'
    | '/admin/roles'
    | '/admin/server'
    | '/admin/users'
    | '/settings/apps'
    | '/settings/connections'
    | '/settings/danger'
    | '/settings/profile'
    | '/settings/security'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/oauth'
    | '/_authenticated/_app'
    | '/_authenticated/_legacy'
    | '/_authenticated/_settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/oauth/consent'
    | '/_authenticated/_app/activity'
    | '/_authenticated/_app/profile'
    | '/_authenticated/_app/requests'
    | '/_authenticated/_app/taste'
    | '/_authenticated/_legacy/oauth-callback'
    | '/_authenticated/_legacy/setup'
    | '/_authenticated/_settings/settings'
    | '/auth/invite/$token'
    | '/_authenticated/_app/'
    | '/_authenticated/_legacy/admin/jobs'
    | '/_authenticated/_legacy/admin/logs'
    | '/_authenticated/_legacy/admin/plugins'
    | '/_authenticated/_legacy/admin/roles'
    | '/_authenticated/_legacy/admin/server'
    | '/_authenticated/_legacy/admin/users'
    | '/_authenticated/_settings/settings/apps'
    | '/_authenticated/_settings/settings/connections'
    | '/_authenticated/_settings/settings/danger'
    | '/_authenticated/_settings/settings/profile'
    | '/_authenticated/_settings/settings/security'
    | '/_authenticated/_settings/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OauthRouteRoute: typeof OauthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oauth': {
      id: '/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof OauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof OauthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/_settings': {
      id: '/_authenticated/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_legacy': {
      id: '/_authenticated/_legacy'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLegacyRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/auth/invite/$token': {
      id: '/auth/invite/$token'
      path: '/invite/$token'
      fullPath: '/auth/invite/$token'
      preLoaderRoute: typeof AuthInviteTokenRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/_settings/settings': {
      id: '/_authenticated/_settings/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_legacy/setup': {
      id: '/_authenticated/_legacy/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedLegacySetupRouteImport
      parentRoute: typeof AuthenticatedLegacyRouteRoute
    }
    '/_authenticated/_legacy/oauth-callback': {
      id: '/_authenticated/_legacy/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof AuthenticatedLegacyOauthCallbackRouteImport
      parentRoute: typeof AuthenticatedLegacyRouteRoute
    }
    '/_authenticated/_app/taste': {
      id: '/_authenticated/_app/taste'
      path: '/taste'
      fullPath: '/taste'
      preLoaderRoute: typeof AuthenticatedAppTasteRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/requests': {
      id: '/_authenticated/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedAppRequestsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/profile': {
      id: '/_authenticated/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/activity': {
      id: '/_authenticated/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedAppActivityRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_settings/settings/': {
      id: '/_authenticated/_settings/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsSettingsRoute
    }
    '/_authenticated/_settings/settings/security': {
      id: '/_authenticated/_settings/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsSettingsRoute
    }
    '/_authenticated/_settings/settings/profile': {
      id: '/_authenticated/_settings/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsSettingsRoute
    }
    '/_authenticated/_settings/settings/danger': {
      id: '/_authenticated/_settings/settings/danger'
      path: '/danger'
      fullPath: '/settings/danger'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsDangerRouteImport
      parentRoute: typeof AuthenticatedSettingsSettingsRoute
    }
    '/_authenticated/_settings/settings/connections': {
      id: '/_authenticated/_settings/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsConnectionsRouteImport
      parentRoute: typeof AuthenticatedSettingsSettingsRoute
    }
    '/_authenticated/_settings/settings/apps': {
      id: '/_authenticated/_settings/settings/apps'
      path: '/apps'
      fullPath: '/settings/apps'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsAppsRouteImport
      parentRoute: typeof AuthenticatedSettingsSettingsRoute
    }
    '/_authenticated/_legacy/admin/users': {
      id: '/_authenticated/_legacy/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedLegacyAdminUsersRouteImport
      parentRoute: typeof AuthenticatedLegacyRouteRoute
    }
    '/_authenticated/_legacy/admin/server': {
      id: '/_authenticated/_legacy/admin/server'
      path: '/admin/server'
      fullPath: '/admin/server'
      preLoaderRoute: typeof AuthenticatedLegacyAdminServerRouteImport
      parentRoute: typeof AuthenticatedLegacyRouteRoute
    }
    '/_authenticated/_legacy/admin/roles': {
      id: '/_authenticated/_legacy/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedLegacyAdminRolesRouteImport
      parentRoute: typeof AuthenticatedLegacyRouteRoute
    }
    '/_authenticated/_legacy/admin/plugins': {
      id: '/_authenticated/_legacy/admin/plugins'
      path: '/admin/plugins'
      fullPath: '/admin/plugins'
      preLoaderRoute: typeof AuthenticatedLegacyAdminPluginsRouteImport
      parentRoute: typeof AuthenticatedLegacyRouteRoute
    }
    '/_authenticated/_legacy/admin/logs': {
      id: '/_authenticated/_legacy/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedLegacyAdminLogsRouteImport
      parentRoute: typeof AuthenticatedLegacyRouteRoute
    }
    '/_authenticated/_legacy/admin/jobs': {
      id: '/_authenticated/_legacy/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedLegacyAdminJobsRouteImport
      parentRoute: typeof AuthenticatedLegacyRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppActivityRoute: typeof AuthenticatedAppActivityRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppRequestsRoute: typeof AuthenticatedAppRequestsRoute
  AuthenticatedAppTasteRoute: typeof AuthenticatedAppTasteRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppActivityRoute: AuthenticatedAppActivityRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppRequestsRoute: AuthenticatedAppRequestsRoute,
  AuthenticatedAppTasteRoute: AuthenticatedAppTasteRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedLegacyRouteRouteChildren {
  AuthenticatedLegacyOauthCallbackRoute: typeof AuthenticatedLegacyOauthCallbackRoute
  AuthenticatedLegacySetupRoute: typeof AuthenticatedLegacySetupRoute
  AuthenticatedLegacyAdminJobsRoute: typeof AuthenticatedLegacyAdminJobsRoute
  AuthenticatedLegacyAdminLogsRoute: typeof AuthenticatedLegacyAdminLogsRoute
  AuthenticatedLegacyAdminPluginsRoute: typeof AuthenticatedLegacyAdminPluginsRoute
  AuthenticatedLegacyAdminRolesRoute: typeof AuthenticatedLegacyAdminRolesRoute
  AuthenticatedLegacyAdminServerRoute: typeof AuthenticatedLegacyAdminServerRoute
  AuthenticatedLegacyAdminUsersRoute: typeof AuthenticatedLegacyAdminUsersRoute
}

const AuthenticatedLegacyRouteRouteChildren: AuthenticatedLegacyRouteRouteChildren =
  {
    AuthenticatedLegacyOauthCallbackRoute:
      AuthenticatedLegacyOauthCallbackRoute,
    AuthenticatedLegacySetupRoute: AuthenticatedLegacySetupRoute,
    AuthenticatedLegacyAdminJobsRoute: AuthenticatedLegacyAdminJobsRoute,
    AuthenticatedLegacyAdminLogsRoute: AuthenticatedLegacyAdminLogsRoute,
    AuthenticatedLegacyAdminPluginsRoute: AuthenticatedLegacyAdminPluginsRoute,
    AuthenticatedLegacyAdminRolesRoute: AuthenticatedLegacyAdminRolesRoute,
    AuthenticatedLegacyAdminServerRoute: AuthenticatedLegacyAdminServerRoute,
    AuthenticatedLegacyAdminUsersRoute: AuthenticatedLegacyAdminUsersRoute,
  }

const AuthenticatedLegacyRouteRouteWithChildren =
  AuthenticatedLegacyRouteRoute._addFileChildren(
    AuthenticatedLegacyRouteRouteChildren,
  )

interface AuthenticatedSettingsSettingsRouteChildren {
  AuthenticatedSettingsSettingsAppsRoute: typeof AuthenticatedSettingsSettingsAppsRoute
  AuthenticatedSettingsSettingsConnectionsRoute: typeof AuthenticatedSettingsSettingsConnectionsRoute
  AuthenticatedSettingsSettingsDangerRoute: typeof AuthenticatedSettingsSettingsDangerRoute
  AuthenticatedSettingsSettingsProfileRoute: typeof AuthenticatedSettingsSettingsProfileRoute
  AuthenticatedSettingsSettingsSecurityRoute: typeof AuthenticatedSettingsSettingsSecurityRoute
  AuthenticatedSettingsSettingsIndexRoute: typeof AuthenticatedSettingsSettingsIndexRoute
}

const AuthenticatedSettingsSettingsRouteChildren: AuthenticatedSettingsSettingsRouteChildren =
  {
    AuthenticatedSettingsSettingsAppsRoute:
      AuthenticatedSettingsSettingsAppsRoute,
    AuthenticatedSettingsSettingsConnectionsRoute:
      AuthenticatedSettingsSettingsConnectionsRoute,
    AuthenticatedSettingsSettingsDangerRoute:
      AuthenticatedSettingsSettingsDangerRoute,
    AuthenticatedSettingsSettingsProfileRoute:
      AuthenticatedSettingsSettingsProfileRoute,
    AuthenticatedSettingsSettingsSecurityRoute:
      AuthenticatedSettingsSettingsSecurityRoute,
    AuthenticatedSettingsSettingsIndexRoute:
      AuthenticatedSettingsSettingsIndexRoute,
  }

const AuthenticatedSettingsSettingsRouteWithChildren =
  AuthenticatedSettingsSettingsRoute._addFileChildren(
    AuthenticatedSettingsSettingsRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsSettingsRoute: typeof AuthenticatedSettingsSettingsRouteWithChildren
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsSettingsRoute:
      AuthenticatedSettingsSettingsRouteWithChildren,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedLegacyRouteRoute: typeof AuthenticatedLegacyRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedLegacyRouteRoute: AuthenticatedLegacyRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthInviteTokenRoute: typeof AuthInviteTokenRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthInviteTokenRoute: AuthInviteTokenRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OauthRouteRouteChildren {
  OauthConsentRoute: typeof OauthConsentRoute
}

const OauthRouteRouteChildren: OauthRouteRouteChildren = {
  OauthConsentRoute: OauthConsentRoute,
}

const OauthRouteRouteWithChildren = OauthRouteRoute._addFileChildren(
  OauthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OauthRouteRoute: OauthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
