/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OauthRouteRouteImport } from './routes/oauth/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/_settings/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app/index'
import { Route as AuthInviteTokenRouteImport } from './routes/auth/invite.$token'
import { Route as AuthenticatedSettingsSetupRouteImport } from './routes/_authenticated/_settings/setup'
import { Route as AuthenticatedSettingsOauthCallbackRouteImport } from './routes/_authenticated/_settings/oauth-callback'
import { Route as AuthenticatedAppWatchlistRouteImport } from './routes/_authenticated/_app/watchlist'
import { Route as AuthenticatedAppLibraryRouteImport } from './routes/_authenticated/_app/library'
import { Route as AuthenticatedSettingsSettingsIndexRouteImport } from './routes/_authenticated/_settings/settings/index'
import { Route as AuthenticatedSettingsSettingsSecurityRouteImport } from './routes/_authenticated/_settings/settings/security'
import { Route as AuthenticatedSettingsSettingsProfileRouteImport } from './routes/_authenticated/_settings/settings/profile'
import { Route as AuthenticatedSettingsSettingsDangerRouteImport } from './routes/_authenticated/_settings/settings/danger'
import { Route as AuthenticatedSettingsSettingsConnectionsRouteImport } from './routes/_authenticated/_settings/settings/connections'
import { Route as AuthenticatedSettingsSettingsAppsRouteImport } from './routes/_authenticated/_settings/settings/apps'
import { Route as AuthenticatedSettingsAdminUsersRouteImport } from './routes/_authenticated/_settings/admin/users'
import { Route as AuthenticatedSettingsAdminServerRouteImport } from './routes/_authenticated/_settings/admin/server'
import { Route as AuthenticatedSettingsAdminRolesRouteImport } from './routes/_authenticated/_settings/admin/roles'
import { Route as AuthenticatedSettingsAdminPluginsRouteImport } from './routes/_authenticated/_settings/admin/plugins'
import { Route as AuthenticatedSettingsAdminLogsRouteImport } from './routes/_authenticated/_settings/admin/logs'
import { Route as AuthenticatedSettingsAdminJobsRouteImport } from './routes/_authenticated/_settings/admin/jobs'

const OauthRouteRoute = OauthRouteRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => OauthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/_settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthInviteTokenRoute = AuthInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedSettingsSetupRoute =
  AuthenticatedSettingsSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsOauthCallbackRoute =
  AuthenticatedSettingsOauthCallbackRouteImport.update({
    id: '/oauth-callback',
    path: '/oauth-callback',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedAppWatchlistRoute =
  AuthenticatedAppWatchlistRouteImport.update({
    id: '/watchlist',
    path: '/watchlist',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppLibraryRoute = AuthenticatedAppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedSettingsSettingsIndexRoute =
  AuthenticatedSettingsSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSettingsSecurityRoute =
  AuthenticatedSettingsSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSettingsProfileRoute =
  AuthenticatedSettingsSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSettingsDangerRoute =
  AuthenticatedSettingsSettingsDangerRouteImport.update({
    id: '/settings/danger',
    path: '/settings/danger',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSettingsConnectionsRoute =
  AuthenticatedSettingsSettingsConnectionsRouteImport.update({
    id: '/settings/connections',
    path: '/settings/connections',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSettingsAppsRoute =
  AuthenticatedSettingsSettingsAppsRouteImport.update({
    id: '/settings/apps',
    path: '/settings/apps',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAdminUsersRoute =
  AuthenticatedSettingsAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAdminServerRoute =
  AuthenticatedSettingsAdminServerRouteImport.update({
    id: '/admin/server',
    path: '/admin/server',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAdminRolesRoute =
  AuthenticatedSettingsAdminRolesRouteImport.update({
    id: '/admin/roles',
    path: '/admin/roles',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAdminPluginsRoute =
  AuthenticatedSettingsAdminPluginsRouteImport.update({
    id: '/admin/plugins',
    path: '/admin/plugins',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAdminLogsRoute =
  AuthenticatedSettingsAdminLogsRouteImport.update({
    id: '/admin/logs',
    path: '/admin/logs',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAdminJobsRoute =
  AuthenticatedSettingsAdminJobsRouteImport.update({
    id: '/admin/jobs',
    path: '/admin/jobs',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/oauth': typeof OauthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/library': typeof AuthenticatedAppLibraryRoute
  '/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/oauth-callback': typeof AuthenticatedSettingsOauthCallbackRoute
  '/setup': typeof AuthenticatedSettingsSetupRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/admin/jobs': typeof AuthenticatedSettingsAdminJobsRoute
  '/admin/logs': typeof AuthenticatedSettingsAdminLogsRoute
  '/admin/plugins': typeof AuthenticatedSettingsAdminPluginsRoute
  '/admin/roles': typeof AuthenticatedSettingsAdminRolesRoute
  '/admin/server': typeof AuthenticatedSettingsAdminServerRoute
  '/admin/users': typeof AuthenticatedSettingsAdminUsersRoute
  '/settings/apps': typeof AuthenticatedSettingsSettingsAppsRoute
  '/settings/connections': typeof AuthenticatedSettingsSettingsConnectionsRoute
  '/settings/danger': typeof AuthenticatedSettingsSettingsDangerRoute
  '/settings/profile': typeof AuthenticatedSettingsSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSettingsSecurityRoute
  '/settings/': typeof AuthenticatedSettingsSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/oauth': typeof OauthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/library': typeof AuthenticatedAppLibraryRoute
  '/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/oauth-callback': typeof AuthenticatedSettingsOauthCallbackRoute
  '/setup': typeof AuthenticatedSettingsSetupRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/admin/jobs': typeof AuthenticatedSettingsAdminJobsRoute
  '/admin/logs': typeof AuthenticatedSettingsAdminLogsRoute
  '/admin/plugins': typeof AuthenticatedSettingsAdminPluginsRoute
  '/admin/roles': typeof AuthenticatedSettingsAdminRolesRoute
  '/admin/server': typeof AuthenticatedSettingsAdminServerRoute
  '/admin/users': typeof AuthenticatedSettingsAdminUsersRoute
  '/settings/apps': typeof AuthenticatedSettingsSettingsAppsRoute
  '/settings/connections': typeof AuthenticatedSettingsSettingsConnectionsRoute
  '/settings/danger': typeof AuthenticatedSettingsSettingsDangerRoute
  '/settings/profile': typeof AuthenticatedSettingsSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSettingsSecurityRoute
  '/settings': typeof AuthenticatedSettingsSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/oauth': typeof OauthRouteRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/_settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_authenticated/_app/library': typeof AuthenticatedAppLibraryRoute
  '/_authenticated/_app/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/_authenticated/_settings/oauth-callback': typeof AuthenticatedSettingsOauthCallbackRoute
  '/_authenticated/_settings/setup': typeof AuthenticatedSettingsSetupRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/_settings/admin/jobs': typeof AuthenticatedSettingsAdminJobsRoute
  '/_authenticated/_settings/admin/logs': typeof AuthenticatedSettingsAdminLogsRoute
  '/_authenticated/_settings/admin/plugins': typeof AuthenticatedSettingsAdminPluginsRoute
  '/_authenticated/_settings/admin/roles': typeof AuthenticatedSettingsAdminRolesRoute
  '/_authenticated/_settings/admin/server': typeof AuthenticatedSettingsAdminServerRoute
  '/_authenticated/_settings/admin/users': typeof AuthenticatedSettingsAdminUsersRoute
  '/_authenticated/_settings/settings/apps': typeof AuthenticatedSettingsSettingsAppsRoute
  '/_authenticated/_settings/settings/connections': typeof AuthenticatedSettingsSettingsConnectionsRoute
  '/_authenticated/_settings/settings/danger': typeof AuthenticatedSettingsSettingsDangerRoute
  '/_authenticated/_settings/settings/profile': typeof AuthenticatedSettingsSettingsProfileRoute
  '/_authenticated/_settings/settings/security': typeof AuthenticatedSettingsSettingsSecurityRoute
  '/_authenticated/_settings/settings/': typeof AuthenticatedSettingsSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/oauth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/oauth/consent'
    | '/library'
    | '/watchlist'
    | '/oauth-callback'
    | '/setup'
    | '/auth/invite/$token'
    | '/admin/jobs'
    | '/admin/logs'
    | '/admin/plugins'
    | '/admin/roles'
    | '/admin/server'
    | '/admin/users'
    | '/settings/apps'
    | '/settings/connections'
    | '/settings/danger'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/oauth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/oauth/consent'
    | '/library'
    | '/watchlist'
    | '/oauth-callback'
    | '/setup'
    | '/auth/invite/$token'
    | '/admin/jobs'
    | '/admin/logs'
    | '/admin/plugins'
    | '/admin/roles'
    | '/admin/server'
    | '/admin/users'
    | '/settings/apps'
    | '/settings/connections'
    | '/settings/danger'
    | '/settings/profile'
    | '/settings/security'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/oauth'
    | '/_authenticated/_app'
    | '/_authenticated/_settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/oauth/consent'
    | '/_authenticated/_app/library'
    | '/_authenticated/_app/watchlist'
    | '/_authenticated/_settings/oauth-callback'
    | '/_authenticated/_settings/setup'
    | '/auth/invite/$token'
    | '/_authenticated/_app/'
    | '/_authenticated/_settings/admin/jobs'
    | '/_authenticated/_settings/admin/logs'
    | '/_authenticated/_settings/admin/plugins'
    | '/_authenticated/_settings/admin/roles'
    | '/_authenticated/_settings/admin/server'
    | '/_authenticated/_settings/admin/users'
    | '/_authenticated/_settings/settings/apps'
    | '/_authenticated/_settings/settings/connections'
    | '/_authenticated/_settings/settings/danger'
    | '/_authenticated/_settings/settings/profile'
    | '/_authenticated/_settings/settings/security'
    | '/_authenticated/_settings/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OauthRouteRoute: typeof OauthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oauth': {
      id: '/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof OauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof OauthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/_settings': {
      id: '/_authenticated/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/auth/invite/$token': {
      id: '/auth/invite/$token'
      path: '/invite/$token'
      fullPath: '/auth/invite/$token'
      preLoaderRoute: typeof AuthInviteTokenRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/_settings/setup': {
      id: '/_authenticated/_settings/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSettingsSetupRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/oauth-callback': {
      id: '/_authenticated/_settings/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof AuthenticatedSettingsOauthCallbackRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_app/watchlist': {
      id: '/_authenticated/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedAppWatchlistRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/library': {
      id: '/_authenticated/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedAppLibraryRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_settings/settings/': {
      id: '/_authenticated/_settings/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/settings/security': {
      id: '/_authenticated/_settings/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/settings/profile': {
      id: '/_authenticated/_settings/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/settings/danger': {
      id: '/_authenticated/_settings/settings/danger'
      path: '/settings/danger'
      fullPath: '/settings/danger'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsDangerRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/settings/connections': {
      id: '/_authenticated/_settings/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsConnectionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/settings/apps': {
      id: '/_authenticated/_settings/settings/apps'
      path: '/settings/apps'
      fullPath: '/settings/apps'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsAppsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/admin/users': {
      id: '/_authenticated/_settings/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedSettingsAdminUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/admin/server': {
      id: '/_authenticated/_settings/admin/server'
      path: '/admin/server'
      fullPath: '/admin/server'
      preLoaderRoute: typeof AuthenticatedSettingsAdminServerRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/admin/roles': {
      id: '/_authenticated/_settings/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedSettingsAdminRolesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/admin/plugins': {
      id: '/_authenticated/_settings/admin/plugins'
      path: '/admin/plugins'
      fullPath: '/admin/plugins'
      preLoaderRoute: typeof AuthenticatedSettingsAdminPluginsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/admin/logs': {
      id: '/_authenticated/_settings/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedSettingsAdminLogsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/admin/jobs': {
      id: '/_authenticated/_settings/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedSettingsAdminJobsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppLibraryRoute: typeof AuthenticatedAppLibraryRoute
  AuthenticatedAppWatchlistRoute: typeof AuthenticatedAppWatchlistRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppLibraryRoute: AuthenticatedAppLibraryRoute,
  AuthenticatedAppWatchlistRoute: AuthenticatedAppWatchlistRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsOauthCallbackRoute: typeof AuthenticatedSettingsOauthCallbackRoute
  AuthenticatedSettingsSetupRoute: typeof AuthenticatedSettingsSetupRoute
  AuthenticatedSettingsAdminJobsRoute: typeof AuthenticatedSettingsAdminJobsRoute
  AuthenticatedSettingsAdminLogsRoute: typeof AuthenticatedSettingsAdminLogsRoute
  AuthenticatedSettingsAdminPluginsRoute: typeof AuthenticatedSettingsAdminPluginsRoute
  AuthenticatedSettingsAdminRolesRoute: typeof AuthenticatedSettingsAdminRolesRoute
  AuthenticatedSettingsAdminServerRoute: typeof AuthenticatedSettingsAdminServerRoute
  AuthenticatedSettingsAdminUsersRoute: typeof AuthenticatedSettingsAdminUsersRoute
  AuthenticatedSettingsSettingsAppsRoute: typeof AuthenticatedSettingsSettingsAppsRoute
  AuthenticatedSettingsSettingsConnectionsRoute: typeof AuthenticatedSettingsSettingsConnectionsRoute
  AuthenticatedSettingsSettingsDangerRoute: typeof AuthenticatedSettingsSettingsDangerRoute
  AuthenticatedSettingsSettingsProfileRoute: typeof AuthenticatedSettingsSettingsProfileRoute
  AuthenticatedSettingsSettingsSecurityRoute: typeof AuthenticatedSettingsSettingsSecurityRoute
  AuthenticatedSettingsSettingsIndexRoute: typeof AuthenticatedSettingsSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsOauthCallbackRoute:
      AuthenticatedSettingsOauthCallbackRoute,
    AuthenticatedSettingsSetupRoute: AuthenticatedSettingsSetupRoute,
    AuthenticatedSettingsAdminJobsRoute: AuthenticatedSettingsAdminJobsRoute,
    AuthenticatedSettingsAdminLogsRoute: AuthenticatedSettingsAdminLogsRoute,
    AuthenticatedSettingsAdminPluginsRoute:
      AuthenticatedSettingsAdminPluginsRoute,
    AuthenticatedSettingsAdminRolesRoute: AuthenticatedSettingsAdminRolesRoute,
    AuthenticatedSettingsAdminServerRoute:
      AuthenticatedSettingsAdminServerRoute,
    AuthenticatedSettingsAdminUsersRoute: AuthenticatedSettingsAdminUsersRoute,
    AuthenticatedSettingsSettingsAppsRoute:
      AuthenticatedSettingsSettingsAppsRoute,
    AuthenticatedSettingsSettingsConnectionsRoute:
      AuthenticatedSettingsSettingsConnectionsRoute,
    AuthenticatedSettingsSettingsDangerRoute:
      AuthenticatedSettingsSettingsDangerRoute,
    AuthenticatedSettingsSettingsProfileRoute:
      AuthenticatedSettingsSettingsProfileRoute,
    AuthenticatedSettingsSettingsSecurityRoute:
      AuthenticatedSettingsSettingsSecurityRoute,
    AuthenticatedSettingsSettingsIndexRoute:
      AuthenticatedSettingsSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthInviteTokenRoute: typeof AuthInviteTokenRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthInviteTokenRoute: AuthInviteTokenRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OauthRouteRouteChildren {
  OauthConsentRoute: typeof OauthConsentRoute
}

const OauthRouteRouteChildren: OauthRouteRouteChildren = {
  OauthConsentRoute: OauthConsentRoute,
}

const OauthRouteRouteWithChildren = OauthRouteRoute._addFileChildren(
  OauthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OauthRouteRoute: OauthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
