/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OauthRouteRouteImport } from './routes/oauth/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/_settings/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app/index'
import { Route as AuthInviteTokenRouteImport } from './routes/auth/invite.$token'
import { Route as AuthenticatedSettingsSetupRouteImport } from './routes/_authenticated/_settings/setup'
import { Route as AuthenticatedSettingsOauthCallbackRouteImport } from './routes/_authenticated/_settings/oauth-callback'
import { Route as AuthenticatedAppWatchlistRouteImport } from './routes/_authenticated/_app/watchlist'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/_app/notifications'
import { Route as AuthenticatedAppLibraryRouteImport } from './routes/_authenticated/_app/library'
import { Route as AuthenticatedSettingsSettingsIndexRouteImport } from './routes/_authenticated/_settings/settings/index'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin/index'
import { Route as AuthenticatedSettingsSettingsSecurityRouteImport } from './routes/_authenticated/_settings/settings/security'
import { Route as AuthenticatedSettingsSettingsProfileRouteImport } from './routes/_authenticated/_settings/settings/profile'
import { Route as AuthenticatedSettingsSettingsNotificationsRouteImport } from './routes/_authenticated/_settings/settings/notifications'
import { Route as AuthenticatedSettingsSettingsDangerRouteImport } from './routes/_authenticated/_settings/settings/danger'
import { Route as AuthenticatedSettingsSettingsConnectionsRouteImport } from './routes/_authenticated/_settings/settings/connections'
import { Route as AuthenticatedSettingsSettingsAppsRouteImport } from './routes/_authenticated/_settings/settings/apps'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin/users'
import { Route as AuthenticatedAdminAdminServerRouteImport } from './routes/_authenticated/_admin/admin/server'
import { Route as AuthenticatedAdminAdminRolesRouteImport } from './routes/_authenticated/_admin/admin/roles'
import { Route as AuthenticatedAdminAdminPluginsRouteImport } from './routes/_authenticated/_admin/admin/plugins'
import { Route as AuthenticatedAdminAdminJobsRouteImport } from './routes/_authenticated/_admin/admin/jobs'
import { Route as AuthenticatedAdminAdminDiagnosticsRouteImport } from './routes/_authenticated/_admin/admin/diagnostics'
import { Route as AuthenticatedAppMediaMediaTypeMediaIdRouteImport } from './routes/_authenticated/_app/media.$mediaType.$mediaId'
import { Route as AuthenticatedAdminAdminNotificationsSettingsRouteImport } from './routes/_authenticated/_admin/admin/notifications/settings'
import { Route as AuthenticatedAdminAdminNotificationsDeliveriesRouteImport } from './routes/_authenticated/_admin/admin/notifications/deliveries'

const OauthRouteRoute = OauthRouteRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => OauthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/_settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthInviteTokenRoute = AuthInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedSettingsSetupRoute =
  AuthenticatedSettingsSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsOauthCallbackRoute =
  AuthenticatedSettingsOauthCallbackRouteImport.update({
    id: '/oauth-callback',
    path: '/oauth-callback',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedAppWatchlistRoute =
  AuthenticatedAppWatchlistRouteImport.update({
    id: '/watchlist',
    path: '/watchlist',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppLibraryRoute = AuthenticatedAppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedSettingsSettingsIndexRoute =
  AuthenticatedSettingsSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedSettingsSettingsSecurityRoute =
  AuthenticatedSettingsSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSettingsProfileRoute =
  AuthenticatedSettingsSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSettingsNotificationsRoute =
  AuthenticatedSettingsSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSettingsDangerRoute =
  AuthenticatedSettingsSettingsDangerRouteImport.update({
    id: '/settings/danger',
    path: '/settings/danger',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSettingsConnectionsRoute =
  AuthenticatedSettingsSettingsConnectionsRouteImport.update({
    id: '/settings/connections',
    path: '/settings/connections',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSettingsAppsRoute =
  AuthenticatedSettingsSettingsAppsRouteImport.update({
    id: '/settings/apps',
    path: '/settings/apps',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminServerRoute =
  AuthenticatedAdminAdminServerRouteImport.update({
    id: '/admin/server',
    path: '/admin/server',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminRolesRoute =
  AuthenticatedAdminAdminRolesRouteImport.update({
    id: '/admin/roles',
    path: '/admin/roles',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPluginsRoute =
  AuthenticatedAdminAdminPluginsRouteImport.update({
    id: '/admin/plugins',
    path: '/admin/plugins',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminJobsRoute =
  AuthenticatedAdminAdminJobsRouteImport.update({
    id: '/admin/jobs',
    path: '/admin/jobs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminDiagnosticsRoute =
  AuthenticatedAdminAdminDiagnosticsRouteImport.update({
    id: '/admin/diagnostics',
    path: '/admin/diagnostics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppMediaMediaTypeMediaIdRoute =
  AuthenticatedAppMediaMediaTypeMediaIdRouteImport.update({
    id: '/media/$mediaType/$mediaId',
    path: '/media/$mediaType/$mediaId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAdminAdminNotificationsSettingsRoute =
  AuthenticatedAdminAdminNotificationsSettingsRouteImport.update({
    id: '/admin/notifications/settings',
    path: '/admin/notifications/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminNotificationsDeliveriesRoute =
  AuthenticatedAdminAdminNotificationsDeliveriesRouteImport.update({
    id: '/admin/notifications/deliveries',
    path: '/admin/notifications/deliveries',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/oauth': typeof OauthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/library': typeof AuthenticatedAppLibraryRoute
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/oauth-callback': typeof AuthenticatedSettingsOauthCallbackRoute
  '/setup': typeof AuthenticatedSettingsSetupRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/admin/diagnostics': typeof AuthenticatedAdminAdminDiagnosticsRoute
  '/admin/jobs': typeof AuthenticatedAdminAdminJobsRoute
  '/admin/plugins': typeof AuthenticatedAdminAdminPluginsRoute
  '/admin/roles': typeof AuthenticatedAdminAdminRolesRoute
  '/admin/server': typeof AuthenticatedAdminAdminServerRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/settings/apps': typeof AuthenticatedSettingsSettingsAppsRoute
  '/settings/connections': typeof AuthenticatedSettingsSettingsConnectionsRoute
  '/settings/danger': typeof AuthenticatedSettingsSettingsDangerRoute
  '/settings/notifications': typeof AuthenticatedSettingsSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSettingsSecurityRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/settings/': typeof AuthenticatedSettingsSettingsIndexRoute
  '/admin/notifications/deliveries': typeof AuthenticatedAdminAdminNotificationsDeliveriesRoute
  '/admin/notifications/settings': typeof AuthenticatedAdminAdminNotificationsSettingsRoute
  '/media/$mediaType/$mediaId': typeof AuthenticatedAppMediaMediaTypeMediaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/oauth': typeof OauthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/library': typeof AuthenticatedAppLibraryRoute
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/oauth-callback': typeof AuthenticatedSettingsOauthCallbackRoute
  '/setup': typeof AuthenticatedSettingsSetupRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/admin/diagnostics': typeof AuthenticatedAdminAdminDiagnosticsRoute
  '/admin/jobs': typeof AuthenticatedAdminAdminJobsRoute
  '/admin/plugins': typeof AuthenticatedAdminAdminPluginsRoute
  '/admin/roles': typeof AuthenticatedAdminAdminRolesRoute
  '/admin/server': typeof AuthenticatedAdminAdminServerRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/settings/apps': typeof AuthenticatedSettingsSettingsAppsRoute
  '/settings/connections': typeof AuthenticatedSettingsSettingsConnectionsRoute
  '/settings/danger': typeof AuthenticatedSettingsSettingsDangerRoute
  '/settings/notifications': typeof AuthenticatedSettingsSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSettingsSecurityRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/settings': typeof AuthenticatedSettingsSettingsIndexRoute
  '/admin/notifications/deliveries': typeof AuthenticatedAdminAdminNotificationsDeliveriesRoute
  '/admin/notifications/settings': typeof AuthenticatedAdminAdminNotificationsSettingsRoute
  '/media/$mediaType/$mediaId': typeof AuthenticatedAppMediaMediaTypeMediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/oauth': typeof OauthRouteRouteWithChildren
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/_settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_authenticated/_app/library': typeof AuthenticatedAppLibraryRoute
  '/_authenticated/_app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/_app/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/_authenticated/_settings/oauth-callback': typeof AuthenticatedSettingsOauthCallbackRoute
  '/_authenticated/_settings/setup': typeof AuthenticatedSettingsSetupRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/_admin/admin/diagnostics': typeof AuthenticatedAdminAdminDiagnosticsRoute
  '/_authenticated/_admin/admin/jobs': typeof AuthenticatedAdminAdminJobsRoute
  '/_authenticated/_admin/admin/plugins': typeof AuthenticatedAdminAdminPluginsRoute
  '/_authenticated/_admin/admin/roles': typeof AuthenticatedAdminAdminRolesRoute
  '/_authenticated/_admin/admin/server': typeof AuthenticatedAdminAdminServerRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/_settings/settings/apps': typeof AuthenticatedSettingsSettingsAppsRoute
  '/_authenticated/_settings/settings/connections': typeof AuthenticatedSettingsSettingsConnectionsRoute
  '/_authenticated/_settings/settings/danger': typeof AuthenticatedSettingsSettingsDangerRoute
  '/_authenticated/_settings/settings/notifications': typeof AuthenticatedSettingsSettingsNotificationsRoute
  '/_authenticated/_settings/settings/profile': typeof AuthenticatedSettingsSettingsProfileRoute
  '/_authenticated/_settings/settings/security': typeof AuthenticatedSettingsSettingsSecurityRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_settings/settings/': typeof AuthenticatedSettingsSettingsIndexRoute
  '/_authenticated/_admin/admin/notifications/deliveries': typeof AuthenticatedAdminAdminNotificationsDeliveriesRoute
  '/_authenticated/_admin/admin/notifications/settings': typeof AuthenticatedAdminAdminNotificationsSettingsRoute
  '/_authenticated/_app/media/$mediaType/$mediaId': typeof AuthenticatedAppMediaMediaTypeMediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/oauth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/oauth/consent'
    | '/library'
    | '/notifications'
    | '/watchlist'
    | '/oauth-callback'
    | '/setup'
    | '/auth/invite/$token'
    | '/admin/diagnostics'
    | '/admin/jobs'
    | '/admin/plugins'
    | '/admin/roles'
    | '/admin/server'
    | '/admin/users'
    | '/settings/apps'
    | '/settings/connections'
    | '/settings/danger'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/admin/'
    | '/settings/'
    | '/admin/notifications/deliveries'
    | '/admin/notifications/settings'
    | '/media/$mediaType/$mediaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/oauth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/oauth/consent'
    | '/library'
    | '/notifications'
    | '/watchlist'
    | '/oauth-callback'
    | '/setup'
    | '/auth/invite/$token'
    | '/admin/diagnostics'
    | '/admin/jobs'
    | '/admin/plugins'
    | '/admin/roles'
    | '/admin/server'
    | '/admin/users'
    | '/settings/apps'
    | '/settings/connections'
    | '/settings/danger'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/admin'
    | '/settings'
    | '/admin/notifications/deliveries'
    | '/admin/notifications/settings'
    | '/media/$mediaType/$mediaId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/oauth'
    | '/_authenticated/_admin'
    | '/_authenticated/_app'
    | '/_authenticated/_settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/oauth/consent'
    | '/_authenticated/_app/library'
    | '/_authenticated/_app/notifications'
    | '/_authenticated/_app/watchlist'
    | '/_authenticated/_settings/oauth-callback'
    | '/_authenticated/_settings/setup'
    | '/auth/invite/$token'
    | '/_authenticated/_app/'
    | '/_authenticated/_admin/admin/diagnostics'
    | '/_authenticated/_admin/admin/jobs'
    | '/_authenticated/_admin/admin/plugins'
    | '/_authenticated/_admin/admin/roles'
    | '/_authenticated/_admin/admin/server'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/_settings/settings/apps'
    | '/_authenticated/_settings/settings/connections'
    | '/_authenticated/_settings/settings/danger'
    | '/_authenticated/_settings/settings/notifications'
    | '/_authenticated/_settings/settings/profile'
    | '/_authenticated/_settings/settings/security'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_settings/settings/'
    | '/_authenticated/_admin/admin/notifications/deliveries'
    | '/_authenticated/_admin/admin/notifications/settings'
    | '/_authenticated/_app/media/$mediaType/$mediaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OauthRouteRoute: typeof OauthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oauth': {
      id: '/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof OauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof OauthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/_settings': {
      id: '/_authenticated/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/auth/invite/$token': {
      id: '/auth/invite/$token'
      path: '/invite/$token'
      fullPath: '/auth/invite/$token'
      preLoaderRoute: typeof AuthInviteTokenRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/_settings/setup': {
      id: '/_authenticated/_settings/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSettingsSetupRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/oauth-callback': {
      id: '/_authenticated/_settings/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof AuthenticatedSettingsOauthCallbackRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_app/watchlist': {
      id: '/_authenticated/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedAppWatchlistRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/notifications': {
      id: '/_authenticated/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/library': {
      id: '/_authenticated/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedAppLibraryRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_settings/settings/': {
      id: '/_authenticated/_settings/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_settings/settings/security': {
      id: '/_authenticated/_settings/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/settings/profile': {
      id: '/_authenticated/_settings/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/settings/notifications': {
      id: '/_authenticated/_settings/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/settings/danger': {
      id: '/_authenticated/_settings/settings/danger'
      path: '/settings/danger'
      fullPath: '/settings/danger'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsDangerRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/settings/connections': {
      id: '/_authenticated/_settings/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsConnectionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_settings/settings/apps': {
      id: '/_authenticated/_settings/settings/apps'
      path: '/settings/apps'
      fullPath: '/settings/apps'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsAppsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/server': {
      id: '/_authenticated/_admin/admin/server'
      path: '/admin/server'
      fullPath: '/admin/server'
      preLoaderRoute: typeof AuthenticatedAdminAdminServerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/roles': {
      id: '/_authenticated/_admin/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/plugins': {
      id: '/_authenticated/_admin/admin/plugins'
      path: '/admin/plugins'
      fullPath: '/admin/plugins'
      preLoaderRoute: typeof AuthenticatedAdminAdminPluginsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/jobs': {
      id: '/_authenticated/_admin/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/diagnostics': {
      id: '/_authenticated/_admin/admin/diagnostics'
      path: '/admin/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AuthenticatedAdminAdminDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_app/media/$mediaType/$mediaId': {
      id: '/_authenticated/_app/media/$mediaType/$mediaId'
      path: '/media/$mediaType/$mediaId'
      fullPath: '/media/$mediaType/$mediaId'
      preLoaderRoute: typeof AuthenticatedAppMediaMediaTypeMediaIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_admin/admin/notifications/settings': {
      id: '/_authenticated/_admin/admin/notifications/settings'
      path: '/admin/notifications/settings'
      fullPath: '/admin/notifications/settings'
      preLoaderRoute: typeof AuthenticatedAdminAdminNotificationsSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/notifications/deliveries': {
      id: '/_authenticated/_admin/admin/notifications/deliveries'
      path: '/admin/notifications/deliveries'
      fullPath: '/admin/notifications/deliveries'
      preLoaderRoute: typeof AuthenticatedAdminAdminNotificationsDeliveriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminDiagnosticsRoute: typeof AuthenticatedAdminAdminDiagnosticsRoute
  AuthenticatedAdminAdminJobsRoute: typeof AuthenticatedAdminAdminJobsRoute
  AuthenticatedAdminAdminPluginsRoute: typeof AuthenticatedAdminAdminPluginsRoute
  AuthenticatedAdminAdminRolesRoute: typeof AuthenticatedAdminAdminRolesRoute
  AuthenticatedAdminAdminServerRoute: typeof AuthenticatedAdminAdminServerRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
  AuthenticatedAdminAdminNotificationsDeliveriesRoute: typeof AuthenticatedAdminAdminNotificationsDeliveriesRoute
  AuthenticatedAdminAdminNotificationsSettingsRoute: typeof AuthenticatedAdminAdminNotificationsSettingsRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminDiagnosticsRoute:
      AuthenticatedAdminAdminDiagnosticsRoute,
    AuthenticatedAdminAdminJobsRoute: AuthenticatedAdminAdminJobsRoute,
    AuthenticatedAdminAdminPluginsRoute: AuthenticatedAdminAdminPluginsRoute,
    AuthenticatedAdminAdminRolesRoute: AuthenticatedAdminAdminRolesRoute,
    AuthenticatedAdminAdminServerRoute: AuthenticatedAdminAdminServerRoute,
    AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
    AuthenticatedAdminAdminNotificationsDeliveriesRoute:
      AuthenticatedAdminAdminNotificationsDeliveriesRoute,
    AuthenticatedAdminAdminNotificationsSettingsRoute:
      AuthenticatedAdminAdminNotificationsSettingsRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppLibraryRoute: typeof AuthenticatedAppLibraryRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppWatchlistRoute: typeof AuthenticatedAppWatchlistRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppMediaMediaTypeMediaIdRoute: typeof AuthenticatedAppMediaMediaTypeMediaIdRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppLibraryRoute: AuthenticatedAppLibraryRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppWatchlistRoute: AuthenticatedAppWatchlistRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppMediaMediaTypeMediaIdRoute:
    AuthenticatedAppMediaMediaTypeMediaIdRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsOauthCallbackRoute: typeof AuthenticatedSettingsOauthCallbackRoute
  AuthenticatedSettingsSetupRoute: typeof AuthenticatedSettingsSetupRoute
  AuthenticatedSettingsSettingsAppsRoute: typeof AuthenticatedSettingsSettingsAppsRoute
  AuthenticatedSettingsSettingsConnectionsRoute: typeof AuthenticatedSettingsSettingsConnectionsRoute
  AuthenticatedSettingsSettingsDangerRoute: typeof AuthenticatedSettingsSettingsDangerRoute
  AuthenticatedSettingsSettingsNotificationsRoute: typeof AuthenticatedSettingsSettingsNotificationsRoute
  AuthenticatedSettingsSettingsProfileRoute: typeof AuthenticatedSettingsSettingsProfileRoute
  AuthenticatedSettingsSettingsSecurityRoute: typeof AuthenticatedSettingsSettingsSecurityRoute
  AuthenticatedSettingsSettingsIndexRoute: typeof AuthenticatedSettingsSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsOauthCallbackRoute:
      AuthenticatedSettingsOauthCallbackRoute,
    AuthenticatedSettingsSetupRoute: AuthenticatedSettingsSetupRoute,
    AuthenticatedSettingsSettingsAppsRoute:
      AuthenticatedSettingsSettingsAppsRoute,
    AuthenticatedSettingsSettingsConnectionsRoute:
      AuthenticatedSettingsSettingsConnectionsRoute,
    AuthenticatedSettingsSettingsDangerRoute:
      AuthenticatedSettingsSettingsDangerRoute,
    AuthenticatedSettingsSettingsNotificationsRoute:
      AuthenticatedSettingsSettingsNotificationsRoute,
    AuthenticatedSettingsSettingsProfileRoute:
      AuthenticatedSettingsSettingsProfileRoute,
    AuthenticatedSettingsSettingsSecurityRoute:
      AuthenticatedSettingsSettingsSecurityRoute,
    AuthenticatedSettingsSettingsIndexRoute:
      AuthenticatedSettingsSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthInviteTokenRoute: typeof AuthInviteTokenRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthInviteTokenRoute: AuthInviteTokenRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OauthRouteRouteChildren {
  OauthConsentRoute: typeof OauthConsentRoute
}

const OauthRouteRouteChildren: OauthRouteRouteChildren = {
  OauthConsentRoute: OauthConsentRoute,
}

const OauthRouteRouteWithChildren = OauthRouteRoute._addFileChildren(
  OauthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OauthRouteRoute: OauthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
