import type { NotificationItemDto } from "../../shared/types";

const now = Date.now();
const mins = (n: number) => now - n * 60_000;
const hours = (n: number) => now - n * 3_600_000;
const days = (n: number) => now - n * 86_400_000;

export const DUMMY_NOTIFICATIONS: NotificationItemDto[] = [
  {
    id: "n1",
    severity: "info",
    category: "media",
    title: "Severance S2E5 is now available",
    body: "Your requested episode has been downloaded and is ready to watch.",
    actionUrl: "/media/severance-s2e5",
    image: null,
    createdAt: mins(4),
    readAt: null,
    audienceKind: "user",
  },
  {
    id: "n2",
    severity: "warn",
    category: "auth",
    title: "Trakt connection expires soon",
    body: "Your Trakt OAuth token expires in 3 days. Reconnect to avoid sync interruptions.",
    actionUrl: "/settings/connections",
    image: null,
    createdAt: mins(22),
    readAt: null,
    audienceKind: "user",
    actions: [
      { label: "Reconnect", url: "/settings/connections", style: "primary" },
      { label: "Dismiss", url: "#", style: "default" },
    ],
  },
  {
    id: "n3",
    severity: "error",
    category: "sync",
    title: "Plex sync failed",
    body: "Watch history sync failed after 6 attempts. Last error: upstream timeout.",
    actionUrl: null,
    image: null,
    createdAt: hours(1),
    readAt: null,
    audienceKind: "admin",
    bodyMarkdown:
      "Watch history sync failed after **6 attempts**. Last error: `upstream timeout`.\nCheck the _Plex_ connection or retry manually.",
  },
  {
    id: "n4",
    severity: "info",
    category: "media",
    title: "The Bear S3 — all episodes available",
    body: "The full season has been processed and added to your library.",
    actionUrl: "/media/the-bear-s3",
    image: {
      url: "https://image.tmdb.org/t/p/w780/bVNfCQPnXRbGHXpApFwDOQ4tJBm.jpg",
      alt: "The Bear season 3 backdrop",
    },
    createdAt: hours(3),
    readAt: hours(2),
    audienceKind: "user",
  },
  {
    id: "n5",
    severity: "info",
    category: "sync",
    title: "TMDB metadata refresh complete",
    body: "1,240 items updated with latest metadata, ratings, and artwork.",
    actionUrl: null,
    image: null,
    createdAt: hours(5),
    readAt: hours(5),
    audienceKind: "admin",
  },
  {
    id: "n6",
    severity: "error",
    category: "system",
    title: "Disk space warning",
    body: "Server storage is at 91% capacity. Clean up or expand before ingestion jobs resume.",
    actionUrl: "/admin/server",
    image: null,
    createdAt: hours(8),
    readAt: null,
    audienceKind: "admin",
    actions: [{ label: "Go to server settings", url: "/admin/server", style: "primary" }],
  },
  {
    id: "n7",
    severity: "info",
    category: "media",
    title: "Dune: Part Three added to watchlist",
    body: "We'll notify you when it becomes available for download.",
    actionUrl: null,
    image: null,
    createdAt: days(1),
    readAt: days(1),
    audienceKind: "user",
  },
  {
    id: "n8",
    severity: "warn",
    category: "auth",
    title: "Jellyfin API key rotated",
    body: "Your Jellyfin API key was rotated by an admin. Re-enter credentials to restore access.",
    actionUrl: "/settings/connections",
    image: null,
    createdAt: days(2),
    readAt: null,
    audienceKind: "user",
  },
];
