export {
  MediaService,
  type MatchingServer,
  type HomeAggregate,
  interpretAggregate,
  type DispatchRequest,
  type AggregateResult,
  dispatch,
  dispatchSingle,
  dispatchAggregate,
  dispatchPrimary,
  dispatchAggregatePerKind,
  dispatchAggregatePerKindStrategy,
  invalidateUserCache,
  compactFromRaw,
  type PluginMediaRaw,
  listEligibleConnections,
  dispatchToConnection,
  type EligibleConnection,
  type TargetedDispatchRequest,
  invokeOne,
  invokeWithTimeout,
  harvestFromOutcomes,
  type InvokeRequest,
  emitAuthExpired,
  markConnectionStatus,
  persistRefreshedCredentials,
  requireCapability,
  scopeForRequest,
  pickSingleConnection,
  resolveConnections,
  type ResolvedConnection,
  identifyItem,
  parseHistoryBase,
  parseItemDate,
  splitCombinedId,
  type RawPluginItem,
  type ItemIdentity,
  setPrimaryConnection,
  clearPrimaryConnection,
  getPrimaryConnection,
  ROW_SORTS,
  encodeCursor,
  decodeCursor,
  listActiveRows,
  listActiveRowsKeyset,
  listActiveRowsOffset,
  getActiveRow,
  hasActiveRows,
  type ActiveRow,
  type PageCursor,
  type RowFilter,
  type RowSort,
  classifyBucket,
  matchesBucket,
  isActiveProgress,
  previewForClassify,
  type PreviewMeta,
  getMatchingServersCached,
  __resetAvailabilityCache,
  enrich,
  type MediaEnrichContext,
  type EnrichResult,
  type EnrichOptions,
  loadProgressMap,
  type ProgressEntry,
  type ProgressMap,
} from "./service";
export {
  MEDIA_EVENTS,
  connectionAuthExpiredPayload,
  type ConnectionAuthExpiredPayload,
} from "./events";
export {
  PluginCallError,
  AllPluginsFailedError,
  mapRequestPluginError,
  normalizeError,
  type InvocationOutcome,
} from "./errors";
export { registerJobs } from "./jobs";
