export {
  MediaService,
  type MatchingServer,
  type HomeAggregate,
  interpretAggregate,
  type DispatchRequest,
  type AggregateResult,
  dispatch,
  dispatchSingle,
  dispatchAggregate,
  dispatchPrimary,
  dispatchAggregatePerKind,
  dispatchAggregatePerKindStrategy,
  invalidateUserCache,
  compactFromRaw,
  type PluginMediaRaw,
  listEligibleConnections,
  dispatchToConnection,
  type EligibleConnection,
  type TargetedDispatchRequest,
  invokeOne,
  invokeWithTimeout,
  harvestFromOutcomes,
  type InvokeRequest,
  emitAuthExpired,
  markConnectionStatus,
  persistRefreshedCredentials,
  requireCapability,
  scopeForRequest,
  pickSingleConnection,
  resolveConnections,
  type ResolvedConnection,
  identifyItem,
  parseHistoryBase,
  parseItemDate,
  splitCombinedId,
  type RawPluginItem,
  type ItemIdentity,
  setPrimaryConnection,
  clearPrimaryConnection,
  getPrimaryConnection,
} from "./service";
export {
  MEDIA_EVENTS,
  connectionAuthExpiredPayload,
  type ConnectionAuthExpiredPayload,
} from "./events";
export {
  PluginCallError,
  AllPluginsFailedError,
  mapRequestPluginError,
  normalizeError,
  type InvocationOutcome,
} from "./errors";
export { registerJobs } from "./jobs";
export type { ActiveRow, RowSort, RowFilter } from "@ent-mcp/shared/media";
export {
  listActiveRows,
  listActiveRowsKeyset,
  getActiveRow,
  listAllActiveRows,
  listAvailableCandidates,
  hasActiveRows,
  allKnownKeys,
  upsertActiveRow,
  softRemoveRow,
  bulkInsertActiveRows,
  trySeedLock,
  clearSeedLock,
  hasUserSeeded,
  listSeededUserIds,
  encodeCursor,
  decodeCursor,
  type PageCursor,
  type UpsertActiveResult,
  type SoftRemoveResult,
} from "./service";
